// ========================================
// Controller Dependencies
// ========================================

const {
  analyzeBusinessRequirements,
} = require("../services/requirementsAnalysisService");
const {
  hasValidRequirementsText,
} = require("../utils/validationUtils");

// ========================================
// Requirements Analysis Controller
// ========================================

/**
 * Handles requests to analyze pasted business requirements.
 *
 * The controller is responsible for HTTP-level workflow only:
 * - Reading the requirements value from the request body
 * - Rejecting invalid input before analysis begins
 * - Delegating process generation to the analysis service
 * - Returning the generated process model
 * - Converting unexpected analysis failures into a consistent API response
 *
 * The controller does not know whether the result was generated by mock data,
 * Claude, OpenAI, Ollama, or another provider. Provider and mode selection stay
 * inside the service layer so the route contract remains stable.
 *
 * @param {import("express").Request} req
 * Express request object containing the submitted requirements.
 *
 * @param {import("express").Response} res
 * Express response object used to return the process model or an error.
 *
 * @returns {Promise<import("express").Response>}
 * The generated process model, validation error, or server error response.
 */
const analyzeRequirements = async (req, res) => {
  const { requirements } = req.body;

  // Reject missing, non-string, or whitespace-only requirements before prompt
  // construction or provider communication begins.
  if (!hasValidRequirementsText(requirements)) {
    return res.status(400).json({
      error: "Business requirements are required.",
    });
  }

  try {
    /**
     * Delegate the complete analysis workflow to the service layer.
     *
     * Depending on backend configuration, the service will either return the
     * deterministic mock model or call the centrally configured AI provider and
     * normalize its response.
     */
    const processModel =
      await analyzeBusinessRequirements(requirements);

    return res.status(200).json(processModel);
  } catch (error) {
    /**
     * Log the complete server-side error for development and operational
     * diagnostics.
     *
     * Provider credentials and request contents should never be added to this
     * log statement. Dedicated structured logging and redaction controls can be
     * introduced before production deployment.
     */
    console.error(
      "Business requirements analysis failed:",
      error
    );

    /**
     * Return a safe user-facing error message.
     *
     * During the current development phase, the original message is returned so
     * provider and configuration failures are easy to diagnose. Production can
     * replace this with standardized public error codes while retaining full
     * internal logs.
     */
    return res.status(500).json({
      error:
        error instanceof Error
          ? error.message
          : "An unexpected error occurred while analyzing the requirements.",
    });
  }
};

module.exports = {
  analyzeRequirements,
};